version: "3.8"

services:
  mysqldb:
    image: 'mysql:8.0.31'
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=12345678
      - MYSQL_DATABASE=twitter
    ports:
      - '3307:3306'
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5
  backend:
    image: litvik/backend-twitter
    restart:
      on-failure
    build: api/.
    ports:
      - "8080:8080"
    depends_on:
      - mysqldb
    environment:
      SPRING_APPLICATION_JSON: '{
                "spring.datasource.url" : "jdbc:mysql://mysqldb:3306/twitter?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=UTC",
                "spring.datasource.username" : "root",
                "spring.datasource.password" : "12345678",
                "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5Dialect",
                "spring.jpa.hibernate.ddl-auto" : "validate"
            }'
  frontend:
    image: litvik/frontend-twitter
    restart: unless-stopped
    build: frontend/.
    ports:
      - "4200:4200"
    depends_on:
      - backend